CREATE TABLE IF NOT EXISTS geofences (
  geofence_id INT AUTO_INCREMENT PRIMARY KEY,
  employer_id INT NOT NULL,
  latitude DECIMAL(10, 7) NOT NULL,
  longitude DECIMAL(10, 7) NOT NULL,
  radius INT NOT NULL COMMENT 'Radius in meters',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (employer_id) REFERENCES employers(employer_id) ON DELETE CASCADE
);
